# Generated by Django 4.2.5 on 2023-10-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('Job', models.TextField()),
                ('JV', models.TextField()),
                ('Batch', models.TextField()),
                ('Ref', models.TextField()),
                ('Acct', models.TextField()),
                ('Acct_Desc', models.TextField(db_column='Acct Desc')),
                ('Dept', models.TextField()),
                ('Dept_Desc', models.TextField(db_column='Dept Desc')),
                ('Tran_Date', models.DateField(db_column='Tran Date', primary_key=True, serialize=False)),
                ('Desc', models.TextField()),
                ('Invoice_Nbr', models.TextField(db_column='Invoice Nbr')),
                ('Amt', models.TextField()),
                ('Acct_Per', models.TextField(db_column='Acct Per')),
                ('Comment', models.TextField()),
                ('Due_Date', models.TextField(db_column='Due Date')),
                ('Chk_Date', models.TextField(db_column='Chk Date')),
                ('Sequence', models.TextField()),
                ('Batch_Close_Date', models.TextField(db_column='Batch Close Date')),
                ('Vend_Cust_Nbr', models.TextField(db_column='Vend/Cust Nbr')),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
    ]
